CREATE DATABASE MEC;
USE MEC;
CREATE TABLE CSE(
Roll_No INT PRIMARY KEY,
Name VARCHAR(20),
Dept VARCHAR(20),
CGPA DECIMAL(3,2),
Passed_Date DATE,
ABC TIME,
Passed_Out YEAR,
Aadhar_No INT UNIQUE,
Gender VARCHAR(7) NOT NULL,
FatherName VARCHAR(20)
);
DESCRIBE COMP_SCI;   -- view the table 
ALTER TABLE CSE ADD MotherName VARCHAR(20);
ALTER TABLE CSE DROP FatherName;
ALTER TABLE CSE RENAME TO COMP_SCI;
ALTER TABLE COMP_SCI RENAME COLUMN ABC TO Placed_Time;
DROP TABLE COMP_SCI;
DROP DATABASE MEC;

SELECT * FROM COMP_SCI; -- view the values in the table
INSERT INTO COMP_SCI 
VALUES(54,'Anusha','CSE',8.68,'2025-10-19','11:11:11',2025,'1910','Female'),
(56,'Barani','CSE',8.43,'2025-04-29','11:10:11',2025,'2904','Male');
INSERT INTO COMP_SCI 
VALUES(26,'Kani','CS',7.93,'Female'),
(12,'Sree','ECE',8.31,'Male');

ALTER TABLE COMP_SCI DROP Placed_Date;
ALTER TABLE COMP_SCI DROP Aadhar_No;
ALTER TABLE COMP_SCI DROP Placed_Time;
ALTER TABLE COMP_SCI DROP Passed_Out;

SELECT * FROM COMP_SCI WHERE GENDER='MALE';
UPDATE COMP_SCI SET DEPT='IT';
SET SQL_SAFE_UPDATES=1;
UPDATE COMP_SCI SET DEPT='ECE' WHERE Roll_No=12;
UPDATE COMP_SCI SET CGPA=7.66 WHERE Roll_No=54;

TRUNCATE TABLE COMP_SCI; -- delete the entire values 

CREATE DATABASE MY_COMPANY;
USE MY_COMPANY;
CREATE TABLE EMPLOYEES_DATA(
EmpID INT PRIMARY KEY,
Name VARCHAR(20),
Department VARCHAR(20),
Salary int 
);
INSERT INTO EMPLOYEES_DATA
VALUES (1,'Alice','HR',50000),
(2,'Bob','IT',60000),
(3,'Carol','IT',75000),
(4,'David','Finance',70000),
(5,'Eve','HR',52000);

SELECT * FROM EMPLOYEES_DATA WHERE Salary BETWEEN 50000 AND 60000 ORDER BY SALARY; 

SELECT NAME,DEPARTMENT FROM EMPLOYEES_DATA ORDER BY SALARY limit 3;





